### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by rafaljosko** [GoogleChromeLabs/wp-native-lazyload#11]
The GPL license cannot be added to Apache.

GNU GPL -----> Apache 2.0 ⛔

Apache 2.0 -----> GPL 3.0 ✅

I hope you will change the license... :)

This component -
https://github.com/…/w…/blob/v2.0/inc/Lazyload/Component.php (GNU GPL 3.0)

Cannot be added to your plugin on Apache 2.0 license

https://wordpress.org/plugins/native-lazyload/#developers

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by felixarntz** [comment]
I'm not sure why you see a license issue here. That code was partially inspired by WP Rig, but has various modifications and updates.
