### ISSUE TITLE
The fallback doesn't work on IE10

### ISSUE THREAD

**Issue by ericvalois** [GoogleChromeLabs/wp-native-lazyload#13]
## Issue Overview

The fallback script seems to work fine on IE11 but not on IE10. Here is the error: 
```
SCRIPT5007: Unable to get property 'src' of undefined or null reference 
lazyload.js, line 1 character 1659
```

## Steps to Reproduce (for bugs)

1. Activate the default WordPress theme Twenty Nineteen.
2. Deactivate all WP plugins except for Native Lazyload
3. Add images to a page with the editor
4. Test the page on a VM with Windows 7 and IE10 

PHP 7.3 - IE10 - Windows 7 - Native Lazy load v1.0.1 - WordPress 5.2.3
## Expected Behavior

Images should display.

## Current Behavior

There are empty spaces instead of images. 

## Screenshots / Video

https://cl.ly/e220a8ac07d9

**Comment by felixarntz** [comment]
Thanks for the report @ericvalois!

Apparently IE < 11 doesn't support the `dataset` property on elements, so one needs to rely directly on the data attributes instead.

I'll create a fix for this shortly.
