### ISSUE TITLE
Cover images outside of `the_content()`

### ISSUE THREAD

**Issue by jlavoie13** [GoogleChromeLabs/wp-native-lazyload#14]
Doesn't have noscript fallback when javascript is disabled.

**Comment by jlavoie13** [comment]
Confirmed the noscript is implemented on images run through `the_content()` but nothing else.

**Comment by swissspidy** [comment]
@jlavoie13 Are you suggesting adding the `noscript` fallback for images outside `the_content`?

**Comment by jlavoie13** [comment]
Yes. It seems like it's a bug if only enabled on `the_content()`.

**Comment by felixarntz** [comment]
@jlavoie13 I completely agree with you that it's weird that the plugin only works on post content at this point.

However, given how WordPress generates content, it's not possible (at least not in a reasonable way) to make such updates to any part of the content from the server-side. The plugin would need to run the entire generated markup through an output buffer, which seems overkill for this type of enhancement, as it has all kinds of side effects.

In the future though, with WordPress moving to enabling full-site editing via Gutenberg, it will become possible to address this issue, which I'll totally do when that becomes feasible.
